### ISSUE TITLE
Steam installer is broken

### ISSUE THREAD

**Issue by n1trux** [EvolutionRTS/Evolution-RTS#15] opened 2015-12-09 12:50 UTC
Being a free game, if this was easy installable on steam it'd gather a much larger player base. I only discovered this on the Linux Game DB and the Steam reviews are pretty shitty. The main point of critique is that it only downloads the Spring engine lobby and not the game itself.

Shouldn't it be top priority to make the game accessible to a larger player base? Maybe as such you could actually gather more developers.

Maybe give it some consideration and love ;)

**Comment by ForbodingAngel** [comment] 2015-12-09 23:33
Umm the steam install installs the lobby, the game and a crap load of maps.

I'm a little lost?

**Comment by db81** [comment] 2015-12-10 05:53
Is this just an impression you got from reading reviews, or was it actually broken for you when you tried it?

The main problem at launch was launcher UI being confusing, making it unclear to people how to start the game and leading some to think there wasn't even a game behind that confusing mess of a launcher. I think most negative reviews can be traced back to this.

The launcher received a makeover recently, but there's now only a trickle of new users.

**Comment by n1trux** [comment] 2015-12-10 16:54
Thanks for your fast reaction.

I did install the game and noticed the following problems:

* When compared to other games of the genre (e.g. Planetary Annihilation), the UX is terrible. After downloading the launcher there's no button which actually starts the game, you have to select another tab. Additionally, on my system I got an error on launch, which is just a folder missing (which is created probably?) and which could fend new users off:
![launcher1](https://cloud.githubusercontent.com/assets/7255542/11721642/11876836-9f65-11e5-9fc2-bb03c29dceec.png)
Tutorial and Wiki both took me to a web page, which is fine – but they actually look like buttons for starting the game. Neither "Skirmish vs Shard" nor "Skirmish vs Survival Spawner" did anything, there wasn't even an error message. None of the options you have are explained in a popup/overlay.

* You then have to select the game version and a map, which got downloaded in my case. The game doesn't really make clear which buttons you have to press. Yes, I know I'm playing dumb here, but 80% of humanity is dumb and the Steam reviews show they can't click on a button which says "select". Maybe there should be a default selection of a training map or sth. like that.
![startgamemenu](https://cloud.githubusercontent.com/assets/7255542/11721744/a90c4dd4-9f65-11e5-9d12-887e4f83c098.png)
I don't know if this is intentional, but "my maps" didn't show anything but a square with a question mark in it.

* After closing the game (which took me about a minute because I didn't notice the "X" in the top right and Esc didn't bring up a menu like in similar games), Steam still thinks the game is running and prevents me from opening the launcher again. In fact, I had to kill the web lobby through my task manager because it was nowhere to be found.

---

I am an advanced user and I can play the game just fine, but with this UI it's no wonder that
>there's now only a trickle of new users.

Don't get me wrong, I appreciate the work you put into the game a lot. It's just hard to find and hard to convince new users to actually try it in the current state. **Please tell me how I could help** – should I create a mockup of a menu I deem better UX-wise?

This is how Warcraft 3 did the main menu 13 years ago:
![wc3beta02](https://cloud.githubusercontent.com/assets/7255542/11721539/94bdaefa-9f64-11e5-82ab-653b3b428ba5.jpg)

And this is how Planetary Annihilation looks today:
![pa_mainmenu](https://cloud.githubusercontent.com/assets/7255542/11722009/f3d26b68-9f66-11e5-9fdb-7ad26ceff5bb.png)

didn't change much, huh? ;)

**Comment by ForbodingAngel** [comment] 2015-12-10 20:30
I really appreciate your feedback here @n1trux , it's extremely useful. I'm at work at the moment, but I'll try to briefly touch and explain a few of the things so that even though it doesn't fix the issue, at least it becomes a bit easier to understand.

* UX
You kinda touched on a lot here, but basically, in a lot of ways I agree, it is very difficult to understand. Weblobby is actually built to accommodate several games, which, in a lot of ways adds more to the confusion. I didn't know that the skirmish buttons didn't work (I never use them). I should also confess that I don't develop the lobby, I only work on the game itself. @db81 is the main lobby dev, and I'm pretty sure your feedback is super helpful for him as well.

I'd like to go back and address your original point about being easy to install. Suffice it to say, I agree. If installation were ezpz and didn't require more than a few clicks it would probably do pretty well. There are several distinct development groups... Engine, Game, Lobby, AI. There isn't a whole lot of overlap between the groups either although we do talk with one another quite often and generally at great length.

Tbh I'm very frustrated about the lobby situation. In a lot of ways that frustration is magnified by the fact that SWL has been more geared towards fully supporting Zero K for the past 6 months or so than anything else. It's frustrating because Evo relies heavily on SWL and if SWL runs into issues for users, then Evo/I take(s) the brunt of the blame. That said, @db81 is just one guy and he has done awesome stuff. I'm sure there are a lot of ways he is frustrated about the entire situation as well. Unfortunately, Evo's player base is "small" (and that's probably being generous at this point). As a result, it doesn't really get a lot of clout. Zero K has a significantly larger playerbase so frankly, it sees most of the love. I'm not upset about it, just frustrated that I have zero control over the situation and at the same time I don't want to disparage anyone, least of all @db81 and SWL devs. It's not anyone's fault and when it comes down to it, we're a bunch of guys working for free on our favorite -time wasters- -on paying spare time jobs- hobbies. Frankly, @db81 is in a far better position to talk on all this than I am. At this point I'm more or less just the peanut gallery.

* Selecting game version and map
The version that comes with steam ships with an older version of the game, but updates are small and quick to download (usually ranging form a few kb to a few mb, rarely any larger than that).

*After closing the game, Steam still thinks the game is running and prevents me from opening the launcher again.
That's new, I'm sure he'll get that fixed up quickly.

I suppose here is where I interject my grumbling that the lobby isn't the "game", blah blah blah. That said, I agree with what you're saying, and regardless of semantics, it is still seen as part and parcel so it doesn't really matter to the end user.

*Please tell me how I could help
Now this is cool :-) God knows I/We desperately need help in all areas. WRT the lobby, I'll let Ikinz ( @db81 ) answer that one.

**Comment by n1trux** [comment] 2015-12-10 22:03
I'm fine with a lobby, but in a time where the people communicate via WhatsApp instead of Facebook and "regular" instant messengers because the sign-up process is automatic, every additional step leads to negative Steam reviews which lead to less users and so on...

Can't we just ditch the lobby altogether and create a real main menu? Sadly I'm not at all familiar with the game engine and would probably rather design UI prototypes than actually rewrite important parts of the game :/
Is that possible with Lua (I suppose this is the main language EvolutionRTS is written in)?

I think a large part why Zero K gets more attention is because they have an actual website. I could help with designing that and maybe put some screenshots on it. People love screenshots.
The Steam page is great already but it nearly scared me off, and I download nethack in a shell and play it with vim keybindings.

Since I don't really know what the differences between Zero K and Evolution are, would it be possible to "join forces" with them?

**Comment by ForbodingAngel** [comment] 2015-12-11 17:06
The lobby handles ALL matchmaking. It is not feasible to not use a lobby.

Joining forces with ZK could not happen for a lot of reasons. Not the least of which is that ZK brute force codes EVERYTHING. Evo does use a lot of elements that were originally part of ZK. For quite a while, ZK was the only project with more than one developer (they still have 5 or 6), so for getting game elements you needed, there was a good chance ZK had something that could work for it. Unfortunately, ZK also has a bad habit of intertwining things in such a way that it works well for ZK, but not for projects trying to borrow from that work.

The "sign up process" for the lobby is registering a username and a password. No email needed and it takes 2 seconds. Whatsapp takes significantly longer. I have to register a phone number, wait on an sms, etc. While I understand your point, this is not really a valid complaint. Yes it would be nice to integrate with steam, but doing so is not so easy (and it's out of my ability anyway, although @db81 has looked into it I think).

Actually there is a lobby being written in lua, so basically you start up the engine and you are put into an "ingame" lobby. This is BY FAR the best case scenario, but there is currently only one guy working on it (Gajop). It isn't glorious work. It's a lot of behind the scenes stuff, but the faster LuaLobby gets developed, the faster all of the games on this engine can switch to it. If you have any lua ability, I'm sure Gajop would be thrilled to have someone to help him with it (Gajop is also an engine dev). The repo for lualobby is here: https://github.com/gajop/liblobby

Sure you could create a real main menu, and it wouldn't even be a terrible idea, but the problem is, it would be depressingly static with none of the abilities or features that the lobby provides (of which the list is long and plentiful). Additionally, unless you were to build rapid support into it, it wouldn't even be able to update itself (rapid breaks things into chunks so that essentially once you have the game, when it updates you only have to download the parts that have changes. So usually updates are miniscule).

**Comment by db81** [comment] 2015-12-11 21:27
The current lobby UI is basically a quick-and-dirty attempt to rectify the situation somewhat — in the long run I'd like a proper evo-specific one of course (and it may look like a real main menu too), without the added complexity of accomodating several games, but in the meantime weblobby already existed and could be repurposed to improve on what was there before: if you describe the UX as terrible, you'd be at a loss for words with the one we had at launch. (weblobby is a general lobby intended to be used for all Spring games, but can also be used as a library to build game-specific lobbies)

I'll look into the skirmish buttons not working, they're supposed to bring you into the battle UI with the game selected and a bot already added and then you'd just click the big green start button to get ingame. They're intended to be the way a new user gets ingame for the first time. Should be renamed into something sane too, "Shard" and "Survival Spawner" don't exactly tell you much.

I think the problem with having to register isn't the inconvenience, but users not expecting it and viewing it as odd at best and shady at worst. Technically it should be possible to use steam login.

The thing with the error message on start is because the new lobby looks for engine files in Spring/engine and the old one looked in Spring/weblobby/engine, but the steam depots haven't been updated to move the engine folder yet. I should've communicated better on that.

LuaLobby has to implement UI on top of Spring engine. There's a Lua UI library for Spring called Chili, but it's nowhere as mature as the html+css stack, so it's still quite an investment, bat gajop seems committed. [Weblobby](https://github.com/springweblobby/swl-website) uses html+js+css with facebook's react for UI.

**Comment by ForbodingAngel** [comment] 2016-02-09 06:10
CLosing due to age and the fact that react is live and fixes a lot of problems mentioned here.

**Closed by ForbodingAngel** 2016-02-09 06:10 UTC
Labels: help wanted
